# Generated by Django 5.1.7 on 2025-04-03 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('reset', 'Reset')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('last_reset', models.DateTimeField(blank=True, null=True)),
                ('router_type', models.CharField(choices=[('head', 'Head'), ('tail', 'Tail'), ('intermediate', 'Intermediate')], default='intermediate', max_length=50)),
                ('parent_router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='routers.router')),
            ],
        ),
    ]
